#!/usr/bin/env python3
"""Generate first-pass analysis artifacts from an aggregated benchmark CSV."""

from __future__ import annotations

import argparse
import csv
import math
from html import escape
from pathlib import Path


ALGORITHM_LABELS = {
    "iterative": "Iterative",
    "recursive": "Divide and Conquer",
    "hybrid_divide_conquer": "Hybrid D&C",
    "strassen": "Strassen",
    "hybrid_strassen": "Hybrid Strassen",
}

ALGORITHM_COLORS = {
    "iterative": "#1f77b4",
    "recursive": "#d62728",
    "hybrid_divide_conquer": "#2ca02c",
    "strassen": "#9467bd",
    "hybrid_strassen": "#ff7f0e",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create SVG plots and a Markdown report from aggregated results."
    )
    parser.add_argument(
        "summary_csv",
        help="Aggregated CSV generated by scripts/aggregate_results.py.",
    )
    parser.add_argument(
        "output_dir",
        nargs="?",
        default="results/analysis",
        help="Directory for generated SVG and Markdown artifacts.",
    )
    return parser.parse_args()


def load_rows(summary_csv: Path) -> list[dict[str, str]]:
    with summary_csv.open(newline="") as summary_file:
        return list(csv.DictReader(summary_file))


def grouped_metric(rows: list[dict[str, str]], metric: str) -> dict[str, list[tuple[int, float]]]:
    grouped: dict[str, list[tuple[int, float]]] = {}

    for row in rows:
        algorithm = row["algorithm"]
        grouped.setdefault(algorithm, []).append(
            (int(row["matrix_size"]), float(row[metric]))
        )

    for points in grouped.values():
        points.sort()

    return grouped


def log10(value: float) -> float:
    return math.log10(value)


def nice_metric(value: float, unit: str) -> str:
    if unit == "seconds":
        if value < 0.001:
            return f"{value * 1_000_000:.1f} us"
        if value < 1.0:
            return f"{value * 1000:.2f} ms"
        return f"{value:.2f} s"

    if unit == "bytes":
        if value == 0:
            return "0 B"
        if value < 1024:
            return f"{value:.0f} B"
        if value < 1024 * 1024:
            return f"{value / 1024:.1f} KiB"
        return f"{value / (1024 * 1024):.1f} MiB"

    return f"{value:.6g}"


def format_axis_value(log_value: float, unit: str) -> str:
    return nice_metric(10 ** log_value, unit)


def render_log_line_chart(
    rows: list[dict[str, str]],
    metric: str,
    output_path: Path,
    title: str,
    y_unit: str,
    note: str,
) -> None:
    width = 1100
    height = 680
    margin_left = 96
    margin_right = 230
    margin_top = 72
    margin_bottom = 86
    plot_width = width - margin_left - margin_right
    plot_height = height - margin_top - margin_bottom

    grouped = grouped_metric(rows, metric)
    x_values = sorted({x for points in grouped.values() for x, _ in points})
    positive_values = [y for points in grouped.values() for _, y in points if y > 0]

    if not positive_values:
        raise ValueError(f"Metric {metric} has no positive values to plot on a log scale")

    x_min = log10(min(x_values))
    x_max = log10(max(x_values))
    y_min = math.floor(log10(min(positive_values)))
    y_max = math.ceil(log10(max(positive_values)))

    if y_min == y_max:
        y_min -= 1
        y_max += 1

    def x_to_px(value: int) -> float:
        return margin_left + ((log10(value) - x_min) / (x_max - x_min)) * plot_width

    def y_to_px(value: float) -> float:
        return margin_top + ((y_max - log10(value)) / (y_max - y_min)) * plot_height

    svg: list[str] = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        f'<text x="{margin_left}" y="38" font-family="Arial, sans-serif" font-size="24" font-weight="700" fill="#111827">{escape(title)}</text>',
        f'<text x="{margin_left}" y="61" font-family="Arial, sans-serif" font-size="13" fill="#4b5563">{escape(note)}</text>',
    ]

    for x_value in x_values:
        x = x_to_px(x_value)
        svg.append(f'<line x1="{x:.2f}" y1="{margin_top}" x2="{x:.2f}" y2="{margin_top + plot_height}" stroke="#e5e7eb" stroke-width="1"/>')
        svg.append(f'<text x="{x:.2f}" y="{height - 46}" text-anchor="middle" font-family="Arial, sans-serif" font-size="12" fill="#374151">{x_value}</text>')

    for y_log in range(y_min, y_max + 1):
        y = margin_top + ((y_max - y_log) / (y_max - y_min)) * plot_height
        svg.append(f'<line x1="{margin_left}" y1="{y:.2f}" x2="{margin_left + plot_width}" y2="{y:.2f}" stroke="#e5e7eb" stroke-width="1"/>')
        svg.append(f'<text x="{margin_left - 12}" y="{y + 4:.2f}" text-anchor="end" font-family="Arial, sans-serif" font-size="12" fill="#374151">{escape(format_axis_value(y_log, y_unit))}</text>')

    svg.extend(
        [
            f'<line x1="{margin_left}" y1="{margin_top + plot_height}" x2="{margin_left + plot_width}" y2="{margin_top + plot_height}" stroke="#111827" stroke-width="1.5"/>',
            f'<line x1="{margin_left}" y1="{margin_top}" x2="{margin_left}" y2="{margin_top + plot_height}" stroke="#111827" stroke-width="1.5"/>',
            f'<text x="{margin_left + plot_width / 2:.2f}" y="{height - 16}" text-anchor="middle" font-family="Arial, sans-serif" font-size="14" fill="#111827">Matrix size (n x n, log scale)</text>',
            f'<text transform="translate(24 {margin_top + plot_height / 2:.2f}) rotate(-90)" text-anchor="middle" font-family="Arial, sans-serif" font-size="14" fill="#111827">{escape(metric)} (log scale)</text>',
        ]
    )

    legend_x = margin_left + plot_width + 36
    legend_y = margin_top + 4

    for index, algorithm in enumerate(ALGORITHM_LABELS):
        points = [(x, y) for x, y in grouped.get(algorithm, []) if y > 0]
        color = ALGORITHM_COLORS[algorithm]
        label = ALGORITHM_LABELS[algorithm]

        if points:
            point_string = " ".join(
                f"{x_to_px(x):.2f},{y_to_px(y):.2f}" for x, y in points
            )
            svg.append(f'<polyline points="{point_string}" fill="none" stroke="{color}" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>')

            for x, y in points:
                svg.append(f'<circle cx="{x_to_px(x):.2f}" cy="{y_to_px(y):.2f}" r="4.5" fill="{color}" stroke="#ffffff" stroke-width="1.5"/>')

        y = legend_y + index * 28
        svg.append(f'<line x1="{legend_x}" y1="{y}" x2="{legend_x + 26}" y2="{y}" stroke="{color}" stroke-width="3"/>')
        svg.append(f'<text x="{legend_x + 36}" y="{y + 4}" font-family="Arial, sans-serif" font-size="13" fill="#111827">{escape(label)}</text>')

    svg.append("</svg>")
    output_path.write_text("\n".join(svg) + "\n", encoding="utf-8")


def best_by_size(rows: list[dict[str, str]], metric: str) -> list[tuple[int, str, float]]:
    best: dict[int, tuple[str, float]] = {}

    for row in rows:
        size = int(row["matrix_size"])
        algorithm = row["algorithm"]
        value = float(row[metric])

        if size not in best or value < best[size][1]:
            best[size] = (algorithm, value)

    return [(size, algorithm, value) for size, (algorithm, value) in sorted(best.items())]


def best_positive_by_size(rows: list[dict[str, str]], metric: str) -> list[tuple[int, str, float]]:
    best: dict[int, tuple[str, float]] = {}

    for row in rows:
        size = int(row["matrix_size"])
        algorithm = row["algorithm"]
        value = float(row[metric])

        if value <= 0:
            continue

        if size not in best or value < best[size][1]:
            best[size] = (algorithm, value)

    return [(size, algorithm, value) for size, (algorithm, value) in sorted(best.items())]


def write_report(rows: list[dict[str, str]], output_path: Path) -> None:
    lines = [
        "# Experimental Summary",
        "",
        "This report is generated from the aggregated benchmark CSV.",
        "",
        "## Fastest Algorithm By Size",
        "",
        "| Matrix size | Algorithm | Mean time |",
        "| --- | --- | ---: |",
    ]

    for size, algorithm, value in best_by_size(rows, "time_seconds_mean"):
        lines.append(
            f"| {size} | {ALGORITHM_LABELS[algorithm]} | {nice_metric(value, 'seconds')} |"
        )

    lines.extend(
        [
            "",
            "## Lowest Tracked Heap Peak By Size",
            "",
            "| Matrix size | Algorithm | Mean tracked heap peak |",
            "| --- | --- | ---: |",
        ]
    )

    for size, algorithm, value in best_by_size(rows, "heap_peak_bytes_mean"):
        lines.append(
            f"| {size} | {ALGORITHM_LABELS[algorithm]} | {nice_metric(value, 'bytes')} |"
        )

    lines.extend(
        [
            "",
            "## Lowest Positive Tracked Heap Peak By Size",
            "",
            "| Matrix size | Algorithm | Mean tracked heap peak |",
            "| --- | --- | ---: |",
        ]
    )

    for size, algorithm, value in best_positive_by_size(rows, "heap_peak_bytes_mean"):
        lines.append(
            f"| {size} | {ALGORITHM_LABELS[algorithm]} | {nice_metric(value, 'bytes')} |"
        )

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- Time statistics are based on the strict multiplication interval recorded by the benchmark.",
            "- Heap statistics include only allocations routed through `tracked_malloc`/`tracked_free`.",
            "- Zero tracked heap values mean the algorithm did not allocate through the tracker for that configuration.",
        ]
    )

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    summary_csv = Path(args.summary_csv)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = load_rows(summary_csv)

    render_log_line_chart(
        rows,
        "time_seconds_mean",
        output_dir / "time_seconds_mean.svg",
        "Mean Execution Time By Algorithm",
        "seconds",
        "Log-log view of mean multiplication time by matrix size.",
    )
    render_log_line_chart(
        rows,
        "heap_peak_bytes_mean",
        output_dir / "heap_peak_bytes_mean.svg",
        "Mean Tracked Heap Peak By Algorithm",
        "bytes",
        "Zero tracked-heap points are omitted from the log-scale plot.",
    )
    write_report(rows, output_dir / "experimental_summary.md")

    print(f"Analysis artifacts saved to {output_dir}")


if __name__ == "__main__":
    main()
